users:
  admins:
  - password: admin
    roles: [ADMIN]
    username: admin
  - password: admin1
    roles: [ADMIN]
    username: admin1
  restusers:
  - password: rest
    roles: [RESTUSER]
    username: rest
  - password: rest1
    roles: [RESTUSER]
    username: rest1
  webusers:
  - password: webuser
    roles: [WEBUSER]
    username: webuser
  - password: webuser1
    roles: [WEBUSER]
    username: webuser1
